### ISSUE TITLE
日志模块缺少方法啊

### ISSUE THREAD

**Issue by lifejwang11** [bjdgyc/poolproxy#1]
日志模块缺少对应的方法
commonLog *slog.**Logger** = slog.**GetStdLog**()

**Comment by bjdgyc** [comment]
什么意思，麻烦具体写一下

**Comment by lifejwang11** [comment]
对的，我是有这个需求，然后我拉下来以后，go build以后因为引用的你的日志方法，这里的日志方法全部没有对应的对象，你可以自己试试？

**Comment by bjdgyc** [comment]
嗯 是有这个问题，我看看吧

**Comment by bjdgyc** [comment]
这个部署在本机，只代理本机流量，跟Twemproxy没法比。
这个项目参考一下就行，很久不维护了

**Comment by lifejwang11** [comment]
哦哦，那Twemproxy其实是包含你这个功能的对吧
